// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgn9gQGUOzZvwj7TAWWynRGFyGdMw1wbY',
    appId: '1:801197961896:web:cb715d402c15faa6cbc89d',
    messagingSenderId: '801197961896',
    projectId: 'vhrproject-35e59',
    authDomain: 'vhrproject-35e59.firebaseapp.com',
    storageBucket: 'vhrproject-35e59.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSa7syV_iBZEnDXOO0txKl8_gBoVx4HUg',
    appId: '1:801197961896:android:24ab92ab3f80b2a4cbc89d',
    messagingSenderId: '801197961896',
    projectId: 'vhrproject-35e59',
    storageBucket: 'vhrproject-35e59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmrfNbnWZTllkzh1vP4eBgNB1YXoT1U6Y',
    appId: '1:801197961896:ios:0b0eb26ad45d32c3cbc89d',
    messagingSenderId: '801197961896',
    projectId: 'vhrproject-35e59',
    storageBucket: 'vhrproject-35e59.appspot.com',
    iosClientId: '801197961896-4ebf78rkacs51odub2se0cc3q01n6duf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vhrProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmrfNbnWZTllkzh1vP4eBgNB1YXoT1U6Y',
    appId: '1:801197961896:ios:0b0eb26ad45d32c3cbc89d',
    messagingSenderId: '801197961896',
    projectId: 'vhrproject-35e59',
    storageBucket: 'vhrproject-35e59.appspot.com',
    iosClientId: '801197961896-4ebf78rkacs51odub2se0cc3q01n6duf.apps.googleusercontent.com',
    iosBundleId: 'com.example.vhrProject',
  );
}
